name: master
channels:
  - defaults
dependencies:
  - python=3.9
  - conda-forge::pygraphviz
  - pip
  - pip:
    - black
    - matplotlib
    - numpy
    - scikit-learn
    - scipy
    - tqdm
    - networkx
    - seaborn
    - jupyterlab
